# Generated by Django 5.2.10 on 2026-01-27 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='detials',
            new_name='details',
        ),
    ]
