# Generated by Django 5.2.10 on 2026-01-28 05:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_rename_detials_list_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='list',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='list',
            name='details',
            field=models.CharField(max_length=100),
        ),
    ]
