# Generated by Django 5.2.10 on 2026-01-28 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_list_complete_alter_list_date_alter_list_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='details',
            field=models.TextField(),
        ),
    ]
